<?php
namespace Tests\Spewia\Controller;

use Spewia\Controller\BaseController;

/**
 * Test class for Container.
 * Generated by PHPUnit on 2012-03-23 at 11:39:33.
 *
 */
class BaseControllerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Response property
     * @var array
     */
    protected $response;

    /**
     * Template property
     * @var array
     */
    protected $template;

    /**
     * Test the Render in order to check that it generates the Reponse and the Template Correctly.
     */
    public function testRender()
    {
        $controller = new TestControllerClass();

        $controller->render();
    }

    /**
     * Test the Render when there is no TemplateDefined because we only need the Response.
     */
    public function testRenderWithoutTemplate()
    {
        $controller = new TestControllerClass();

        $controller->render();
    }
}

class TestControllerClass extends BaseController {}
