<?php
namespace Tests\Spewia\DependencyInjection;

use Spewia\DependencyInjection\Container;

/**
 * Test class for Container.
 * Generated by PHPUnit on 2012-03-23 at 11:39:33.
 *
 */
class ContainerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Container
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Container(array(
            'foo' => array(
                'class' => '\Tests\Spewia\DependencyInjection\Foo'
            ),
            'bar' => array(
                'class' => '\Tests\Spewia\DependencyInjection\Bar',
                'constructor_parameters' => array(
                    array(
                        'type'  => 'service',
                        'id'    => 'foo'
                    ),
                    array(
                        'type'  => 'constant',
                        'value' => 'string'
                    )
                )
            ),
            'foobar' => array(
                'class' => '\Tests\Spewia\DependencyInjection\FooBar',
                'constructor_parameters' => array(
                    array(
                        'type'  => 'service',
                        'id'    => 'bar2'
                    )
                )
            ),
            'bar2' => array(
                'class' => '\Tests\Spewia\DependencyInjection\Bar',
                'constructor_parameters' => array(
                    array(
                        'type'  => 'service',
                        'id'    => 'foobar'
                    ),
                    array(
                        'type'  => 'constant',
                        'value' => 'string'
                    )
                )
            )
        ));
    }

    public function testGetWithNoDependencies()
    {
        $return = $this->object->get('foo');

        $this->assertInstanceOf(
            '\Tests\Spewia\DependencyInjection\Foo', $return,
            'The key "foo" expected an instance of type "Foo".');
    }

    public function testMultipleGetCalls()
    {
        $first = $this->object->get('foo');
        $second = $this->object->get('foo');

        $this->assertSame($first, $second,
            'Two calls on the same key should return the same object.');
    }

    public function testGetWithDependencies()
    {
        $return = $this->object->get('bar');

        $this->assertInstanceOf('\Tests\Spewia\DependencyInjection\Bar', $return,
            'The key "bar" expected an instance of type "Bar".');

        $foo = $this->object->get('foo');

        $this->assertSame($foo, $return->getFoo(),
            'The "foo" key and the embedded "foo" element should be the same.');

        $this->assertEquals('string', $return->getString(),
            'The "string", element to be embedded should have the value "string".');
    }

    /**
     * @expectedException \Spewia\DependencyInjection\Exception\CircularDependencyException
     */
    public function testGetWithCircularDependency()
    {
        $this->object->get('foobar');
    }

    /**
     * @expectedException \Spewia\DependencyInjection\Exception\ServiceNotFoundException
     */
    public function testGetNonExistingService()
    {
        $this->object->get('unexisting_service');
    }
}

class Foo
{
}

class Bar
{
    protected $foo;
    protected $string;

    public function __construct(Foo $foo, $string)
    {
        $this->foo = $foo;
        $this->string = $string;
    }

    public function getFoo()
    {
        return $this->foo;
    }

    public function getString()
    {
        return $this->string;
    }
}

class FooBar extends Foo
{
    public function __construct(Bar $bar)
    {
        $this->bar = $bar;
    }

    public function setFoo(Foo $foo)
    {

    }
}